[package]
name = "rvkp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.14.1"
image = "0.24.8"
once_cell = "1.19.0"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
winit = "0.29.10"
